version: '3.8'

services:
  date_generator:
    build: .
    container_name: date_generator_container
    volumes:
      - .:/app
    entrypoint: ["python", "-m", "date_generator.generator"]

  date_processor:
    build: .
    container_name: date_processor_container
    volumes:
      - .:/app
    entrypoint: ["python", "-m", "date_processor.processor"]

  pytest:
    build: .
    container_name: pytest_container
    volumes:
      - .:/app
    command: pytest